In [1]:
import pandas as pd
import numpy as np

In [4]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [5]:
train['Age'] = train['Age'].fillna(train['Age'].median())
train['Sex'] = train['Sex'].map({'male':1,'female':0})
train['Embarked'] = train['Embarked'].map({'S':3,'C':2,'Q':1})
# train.drop(['PassengerId','Name','Ticket','Cabin'],axis="columns",inplace=True)
train['Family'] = train['SibSp']+train['Parch']
train.drop(['PassengerId','Name','Ticket','Cabin','SibSp','Parch'],axis="columns",inplace=True)

In [6]:
train.head()

Survived  Pclass  Sex   Age     Fare  Embarked  Family
0         0       3    1  22.0   7.2500         3       1
1         1       1    0  38.0  71.2833         2       1
2         1       3    0  26.0   7.9250         3       0
3         1       1    0  35.0  53.1000         3       1
4         0       3    1  35.0   8.0500         3       0

In [7]:
test['Age'] = test['Age'].fillna(test['Age'].median())
test['Fare'] = test['Fare'].fillna(test['Fare'].median())
# test.drop(['Name','Ticket','Cabin'],axis="columns",inplace=True)
test['Sex'] = test['Sex'].map({'male':1,'female':0})
test['Embarked'] = test['Embarked'].map({'S':3,'C':2,'Q':1})
test['Family'] = test['SibSp']+test['Parch']
test.drop(['Name','Ticket','Cabin','SibSp','Parch'],axis="columns",inplace=True)

In [8]:
test.head()

PassengerId  Pclass  Sex   Age     Fare  Embarked  Family
0          892       3    1  34.5   7.8292         1       0
1          893       3    0  47.0   7.0000         3       1
2          894       2    1  62.0   9.6875         1       0
3          895       3    1  27.0   8.6625         3       0
4          896       3    0  22.0  12.2875         3       2

In [9]:
X_train = train.iloc[:,1:]
Y_train = train.iloc[:,0]
X_test = test.iloc[:,1:]

In [10]:
X_train

Pclass  Sex   Age     Fare  Embarked  Family
0         3    1  22.0   7.2500         3       1
1         1    0  38.0  71.2833         2       1
2         3    0  26.0   7.9250         3       0
3         1    0  35.0  53.1000         3       1
4         3    1  35.0   8.0500         3       0
..      ...  ...   ...      ...       ...     ...
886       2    1  27.0  13.0000         3       0
887       1    0  19.0  30.0000         3       0
888       3    0  28.0  23.4500         3       3
889       1    1  26.0  30.0000         2       0
890       3    1  32.0   7.7500         1       0

[891 rows x 6 columns]

In [11]:
X_test

Pclass  Sex   Age      Fare  Embarked  Family
0         3    1  34.5    7.8292         1       0
1         3    0  47.0    7.0000         3       1
2         2    1  62.0    9.6875         1       0
3         3    1  27.0    8.6625         3       0
4         3    0  22.0   12.2875         3       2
..      ...  ...   ...       ...       ...     ...
413       3    1  27.0    8.0500         3       0
414       1    0  39.0  108.9000         2       0
415       3    1  38.5    7.2500         3       0
416       3    1  27.0    8.0500         3       0
417       3    1  27.0   22.3583         2       2

[418 rows x 6 columns]

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,4])], remainder='passthrough')
X_train = ct.fit_transform(X_train)

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,4])], remainder='passthrough')
X_test = ct.fit_transform(X_test)

In [14]:
X_train[0]

array([ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.  ,  1.  , 22.  ,  7.25,
        1.  ])

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
ct = ColumnTransformer([('xyz',StandardScaler(),[7,8])], remainder='passthrough')
X_train = ct.fit_transform(X_train)
ct = ColumnTransformer([('xyz',StandardScaler(),[7,8])], remainder='passthrough')
X_test = ct.fit_transform(X_test)

In [174]:
X_train[:5,2]

array([0., 1., 0., 1., 0.])

In [16]:
from sklearn.model_selection import train_test_split
data_tr, data_te, result_tr, result_te = train_test_split(X_train, Y_train, test_size=0.2, random_state=0)

In [17]:
from sklearn.linear_model import LogisticRegression 
classifier = LogisticRegression(solver='liblinear',random_state=0) 
classifier.fit(data_tr, result_tr)

LogisticRegression(random_state=0, solver='liblinear')

In [19]:
pred = classifier.predict(data_te)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(result_te, pred)
print(cm)
accuracy_score(result_te, pred)

[[95 15]
 [18 51]]


0.8156424581005587

In [25]:
from sklearn.linear_model import LogisticRegression 
classifier = LogisticRegression(solver='liblinear',random_state=0) 
classifier.fit(X_train, Y_train)

LogisticRegression(random_state=0, solver='liblinear')

In [26]:
pred = classifier.predict(X_test)

In [27]:
pd.DataFrame(pred).to_csv('sol_logreg.csv')